DOMAIN_KEYWORDS = {
    "Criminal": [
        "murder",
        "ipc",
        "theft",
        "assault",
        "rape",
        "kidnapping",
        "bail",
        "fir",
        "arrest",
        "crpc",
        "criminal",
        "offense",
        "crime",
        "punishment",
        "imprisonment",
        "cognizable",
    ],
    "Civil": [
        "contract",
        "property",
        "civil",
        "damages",
        "injunction",
        "specific performance",
        "tort",
        "negligence",
        "nuisance",
        "easement",
        "suit",
        "plaintiff",
        "defendant",
    ],
    "Constitutional": [
        "constitution",
        "fundamental right",
        "article 21",
        "article 19",
        "writ",
        "habeas corpus",
        "mandamus",
        "pil",
        "supreme court",
        "high court",
        "parliament",
        "amendment",
        "directive principles",
    ],
    "Family": [
        "divorce",
        "marriage",
        "custody",
        "maintenance",
        "alimony",
        "adoption",
        "guardianship",
        "matrimonial",
        "dowry",
        "hindu marriage act",
        "muslim personal law",
        "succession",
    ],
    "Property": [
        "property",
        "land",
        "deed",
        "title",
        "registry",
        "mutation",
        "tenancy",
        "rent",
        "lease",
        "mortgage",
        "transfer of property",
        "benami",
        "encroachment",
    ],
    "Labour": [
        "employment",
        "labour",
        "worker",
        "salary",
        "termination",
        "pf",
        "esic",
        "gratuity",
        "minimum wage",
        "industrial dispute",
        "posh",
        "workplace",
        "employee",
    ],
    "Corporate": [
        "company",
        "corporate",
        "director",
        "shareholder",
        "mca",
        "roc",
        "sebi",
        "ipo",
        "merger",
        "acquisition",
        "compliance",
        "llp",
        "startup",
        "incorporation",
    ],
    "Tax": [
        "tax",
        "income tax",
        "gst",
        "tds",
        "itr",
        "assessment",
        "refund",
        "penalty",
        "appeal",
        "tribunal",
        "revenue",
        "customs",
        "excise",
    ],
}


def classify_domain(query: str) -> str:
    query_lower = query.lower()
    scores = {}
    for domain, keywords in DOMAIN_KEYWORDS.items():
        score = sum(1 for keyword in keywords if keyword in query_lower)
        if score > 0:
            scores[domain] = score
    if not scores:
        return "General"
    return max(scores, key=scores.get)
